services:
  db:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_MASTER_DSN=postgres://postgres:postgres@db:5432/notifications?sslmode=disable
      - DB_SLAVE_DSNS=postgres://postgres:postgres@db:5432/notifications?sslmode=disable
    depends_on:
      - db
  
#   rabbitmq:
#     image: rabbitmq:3-management
#     hostname: rabbitmq
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     environment:
#       RABBITMQ_DEFAULT_USER: guest
#       RABBITMQ_DEFAULT_PASS: guest
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq/mnesia
#     healthcheck:
#       test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

volumes:
  postgres_data:
#   rabbitmq_data: