CREATE TABLE IF NOT EXISTS NOTIFICATIONS(
    ID SERIAL PRIMARY KEY,
    TEXT VARCHAR(256) NOT NULl,
    STATUS VARCHAR(64) NOT NULL DEFAULT 'CREATED',
    SENDTIME TIMESTAMP NOT NULL,
    USERID INT NOT NULL 
);