services:
  db:
    image: postgres:15
    container_name: shortener-db
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_MASTER_DSN=postgres://postgres:postgres@db:5432/notifications?sslmode=disable
      - DB_SLAVE_DSNS=postgres://postgres:postgres@db:5432/notifications?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
